sudo: false
language: go
go:
  - 1.8
env:
  - PACKER_VERSION=0.12.2 \
    PACKER_PLUGIN_BIN=packer-builder-vagrant
script:
  - ln -s ${TRAVIS_BUILD_DIR} ${GOPATH}/src/github.com/${TRAVIS_REPO_SLUG}
  - make dist
deploy:
  - provider: releases
    api_key: ${GITHUB_API_KEY}
    file_glob: true
    file:
      - build/packer-${PACKER_VERSION}_${PACKER_PLUGIN_BIN}*
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
