sudo: false
language: go
env:
  - PACKER_VERSION=0.11.0
go:
  - 1.7
install:
  - go get github.com/mitchellh/gox
script:
  - ln -s ${TRAVIS_BUILD_DIR} ${GOPATH}/src/github.com/${TRAVIS_REPO_SLUG}
  - gox -arch="amd64" -os="darwin linux windows" -output "build/packer-${PACKER_VERSION}_{{.Dir}}_{{.OS}}_{{.Arch}}" github.com/${TRAVIS_REPO_SLUG}
deploy:
  - provider: releases
    api_key: ${GITHUB_API_KEY}
    file:
      - build/packer-${PACKER_VERSION}_packer-builder-vagrant_darwin_amd64
      - build/packer-${PACKER_VERSION}_packer-builder-vagrant_linux_amd64
      - build/packer-${PACKER_VERSION}_packer-builder-vagrant_windows_amd64.exe
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
